name: Build WebAPK

on:
  push:
    branches:
      - main  # Замініть на вашу основну гілку, якщо вона інша

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-31" "platform-tools" "build-tools;31.0.0"
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Download Keystore
        # Завантажте ваш keystore з безпечного місця або збережіть його як секрет GitHub і отримайте тут
        run: |
          curl -o android.keystore https://formidable.bond/app/android.keystore

      - name: Initialize Bubblewrap
        # Використання Bubblewrap для створення WebAPK на основі вашого маніфесту
        run: |
          bubblewrap init --manifest=https://formidable.bond/app/manifest.json --packageId=bond.formidable.app

      - name: Build WebAPK
        # Створення WebAPK із використанням збереженого keystore
        env:
          KEYSTORE_PASSWORD: qwerty
          KEY_PASSWORD: qwerty
          KEY_ALIAS: android
        run: |
          bubblewrap build --skipPwaValidation

      - name: Upload APK
        # Завантаження згенерованого WebAPK як артефакту
        uses: actions/upload-artifact@v3
        with:
          name: webapk-release-signed.apk
          path: ./output/app-release-signed.apk
