name: Build and Release APK

on:
  push:
    branches:
      - main  # Замініть на вашу основну гілку, якщо вона відрізняється

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        env:
          KEYSTORE_PASSWORD: qwerty
          KEY_PASSWORD: qwerty
          KEY_ALIAS: android
        run: |
          bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed.apk
          path: ./build/output/app-release-signed.apk
